# Generated by Django 6.0.5 on 2026-05-26 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_ok', 'Connexion réussie'), ('login_fail', 'Tentative de connexion échouée'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('pw_reset', 'Réinitialisation mot de passe'), ('upload', 'Upload de fichier'), ('order', 'Commande passée'), ('profile_edit', 'Modification du profil'), ('access_denied', 'Accès refusé'), ('rate_limited', 'Trop de tentatives')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('details', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal de sécurité',
                'verbose_name_plural': 'Journaux de sécurité',
                'ordering': ['-timestamp'],
            },
        ),
    ]
