# Generated by Django 6.0.5 on 2026-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Image d'accueil")),
                ('hero_titre', models.CharField(default='Bienvenue sur BKLbusiness', max_length=200, verbose_name="Titre d'accueil")),
                ('hero_description', models.TextField(default='Découvrez notre catalogue de produits et services.', verbose_name="Description d'accueil")),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
    ]
