"""
Migration de réparation : crée la table catalog_sitesettings si elle manque.

Contexte :
    La migration 0002_sitesettings est marquée comme appliquée dans la table
    django_migrations, mais la table catalog_sitesettings n'a jamais été créée
    dans PostgreSQL. Cela arrive quand la base a été restaurée via un dump
    contenant les enregistrements django_migrations.

Cette migration :
    1. Crée la table catalog_sitesettings si elle n'existe pas
    2. Recrée les colonnes manquantes si la table existe mais est incomplète
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sitesettings'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "catalog_sitesettings" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "hero_image" varchar(100) NULL,
                "hero_titre" varchar(200) NOT NULL,
                "hero_description" text NOT NULL
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "catalog_sitesettings" CASCADE;
            """,
            state_operations=[
                migrations.CreateModel(
                    name='SiteSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Image d'accueil")),
                        ('hero_titre', models.CharField(default='Bienvenue sur BKLbusiness', max_length=200, verbose_name="Titre d'accueil")),
                        ('hero_description', models.TextField(default='Découvrez notre catalogue de produits et services.', verbose_name="Description d'accueil")),
                    ],
                    options={
                        'verbose_name': 'Paramètres du site',
                    },
                ),
            ],
        ),
    ]
