"""
Migration de réparation : crée la table catalog_sitesettings si elle manque.

Contexte :
    La migration 0002_sitesettings est marquée comme appliquée dans la table
    django_migrations, mais la table catalog_sitesettings n'a jamais été créée
    dans PostgreSQL. Cela arrive quand la base a été restaurée via un dump
    contenant les enregistrements django_migrations sans la table réelle.

Cette migration :
    - Utilise state_operations pour déclarer le modèle dans l'état Django
      (nécessaire pour que les migrations futures puissent y faire référence)
    - Utilise database_operations pour créer physiquement la table
      avec la syntaxe adaptée au moteur de base de données
"""

from django.db import migrations, models


def _create_sitesettings_table(apps, schema_editor):
    """Crée la table catalog_sitesettings si elle n'existe pas."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS catalog_sitesettings (
                id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                hero_image VARCHAR(100) NULL,
                hero_titre VARCHAR(200) NOT NULL,
                hero_description TEXT NOT NULL
            );
        """)
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS catalog_sitesettings (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                hero_image VARCHAR(100) NULL,
                hero_titre VARCHAR(200) NOT NULL,
                hero_description TEXT NOT NULL
            );
        """)
    else:
        # Fallback générique (approximatif)
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS catalog_sitesettings (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                hero_image VARCHAR(100) NULL,
                hero_titre VARCHAR(200) NOT NULL,
                hero_description TEXT NOT NULL
            );
        """)


def _drop_sitesettings_table(apps, schema_editor):
    """Supprime la table catalog_sitesettings (reverse)."""
    schema_editor.execute("DROP TABLE IF EXISTS catalog_sitesettings CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sitesettings'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SiteSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Image d'accueil")),
                        ('hero_titre', models.CharField(default='Bienvenue sur BKLbusiness', max_length=200, verbose_name="Titre d'accueil")),
                        ('hero_description', models.TextField(default='Découvrez notre catalogue de produits et services.', verbose_name="Description d'accueil")),
                    ],
                    options={
                        'verbose_name': 'Paramètres du site',
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=_create_sitesettings_table,
                    reverse_code=_drop_sitesettings_table,
                ),
            ],
        ),
    ]
